aws_region                = "us-east-1"
image_bucket_name         = "rekognition-image-bucket-prod"
sqs_queue_name            = "rekognition-image-queue-prod"
presigned_url_lambda_name = "rekognition-presigned-url-lambda-prod"
rekognition_lambda_name   = "rekognition-consumer-lambda-prod"
api_name                  = "rekognition-presigned-url-api-prod"
upload_prefix             = "uploads/"